const productos = [
  {
    id: 1,
    nombre: "Gabinete Gamer Atx Rgb",
    precio: 34000,
    img: "photo/gabinete.png",
    cantidad: 1,
  },
  {
    id: 2,
    nombre: "Mother Gigabyte A520",
    precio: 29000,
    img: "photo/mother.png",
    cantidad: 1,
  },
  {
    id: 3,
    nombre: "AMD Ryzen 5 4600g",
    precio: 55000,
    img: "photo/cpu.png",
    cantidad: 1,
  },
  {
    id: 4,
    nombre: "Ram 2x8gb 3600Mhz",
    precio: 43000,
    img: "photo/ram.png",
    cantidad: 1,
  },
  {
    id: 5,
    nombre: "Kingston SSD 960gb",
    precio: 24000,
    img: "photo/ssd.png",
    cantidad: 1,
  },
  {
    id: 6,
    nombre: "RX 570 8gb DDR5",
    precio: 90000,
    img: "photo/vga.png",
    cantidad: 1,
  },
  {
    id: 7,
    nombre: "Fuente Asus 860w",
    precio: 70000,
    img: "photo/fuente.png",
    cantidad: 1,
  },
  {
    id: 8,
    nombre: "Teclado Gamer Redragon",
    precio: 6000,
    img: "photo/teclado.png",
    cantidad: 1,
  },
  {
    id: 9,
    nombre: "Mouse 10.000dpi",
    precio: 4000,
    img: "photo/mouse.png",
    cantidad: 1,
  },
  {
    id: 10,
    nombre: "Parlantes Logitech 160w",
    precio: 39000,
    img: "photo/parlantes.png",
    cantidad: 1,
  },
  {
    id: 11,
    nombre: "Notebook Asus Ryzen9",
    precio: 54000,
    img: "photo/notebook.png",
    cantidad: 1,
  },
  {
    id: 12,
    nombre: "Monitor Samsung 144Hz",
    precio: 76000,
    img: "photo/monitor.png",
    cantidad: 1,
  },
];
